name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

permissions:
  contents: write


jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
        uses: actions/checkout@v3

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test
        working_dir: rust_impl
